<?php /** @var $block Devlat\RelatedProducts\Block\Related */ ?>
<div id="related-products">
    <div id="title" data-bind="scope: 'title'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
    <div id="products" data-bind="scope: 'products'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
</div>

<script type="text/x-magento-init">
    {
        "#related-products": {
            "Magento_Ui/js/core/app": <?= $block->getJsLayout() ?>
        }
    }
</script>
