<div class="btn-placeholder-container">
    <button class="btn-placeholder-toggle" id="<?= $block->getId() ?>">
        <span><?php echo $block->escapeHtml($block->getButtonLabel()); ?></span>
    </button>
</div>
<span class="placeholder-message-alert" id="placeholder_alert"></span>

<script type="text/x-magento-init">
  {
      ".btn-placeholder-toggle": {
          "showHideImage": {
            "url": "<?= /** @noEscape  */ $block->getUrl('placeholder/catalog/productimage')?>"
          }
      }
  }

</script>
